# syntax=docker/dockerfile:1.4
FROM registry.access.redhat.com/ubi9/go-toolset:1.24 AS builder

USER root
WORKDIR /app

COPY go.mod go.sum Makefile ./
COPY vendor/ vendor/
COPY cmd/ cmd/
COPY pkg/ pkg/

RUN --mount=type=cache,target=/root/.cache/go-build \
    make csi-build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y ca-certificates && microdnf clean all

COPY --from=builder /app/bin/bpffs-csi-driver /bpffs-csi-driver

ENTRYPOINT ["/bpffs-csi-driver"]
