# syntax=docker/dockerfile:1.4
# Fast build: copies pre-built static binary from host instead of
# compiling in container.
#
# Usage:
#   make docker-build-bpfman-fast
#
# Requires:
#   make bpfman-build

ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM ${BASE_IMAGE}

COPY bin/bpfman /bpfman
COPY testdata/stats.o /opt/bpf/stats.o

ENV BPFMAN_MODE=bpfman-rpc
ENTRYPOINT ["/bpfman"]
