# syntax=docker/dockerfile:1.4
# Inject pre-built static binary into upstream bpfman image.
#
# Usage:
#   make docker-build-bpfman-upstream
#
# Requires:
#   make bpfman-build

ARG BPFMAN_IMAGE=quay.io/bpfman/bpfman:latest

FROM ${BPFMAN_IMAGE}

COPY bin/bpfman /bpfman
RUN ln -sf /bpfman /bpfman-rpc && ln -sf /bpfman /bpfman-ns

# Override upstream ENTRYPOINT which passes --timeout=0 (not supported by Go daemon)
ENTRYPOINT ["/bpfman-rpc"]
