# syntax=docker/dockerfile:1.4
# Build bpfman image for operator integration testing.
#
# Usage:
#   make docker-build-bpfman-upstream
#
# Requires:
#   make bpfman-build

ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest
FROM ${BASE_IMAGE}

COPY bin/bpfman /bpfman

ENV BPFMAN_MODE=bpfman-rpc
ENV BPFMAN_PPROF_ADDRESS=localhost:6060
ENTRYPOINT ["/bpfman"]
