# syntax=docker/dockerfile:1.4
# Fast build: copies pre-built static binary from host instead of
# compiling in container.
#
# Usage:
#   make docker-build-bpfman-fast
#
# Requires:
#   make bpfman-build

FROM scratch

COPY bin/bpfman /bpfman
COPY bin/bpfman /bpfman-rpc
COPY bin/bpfman /bpfman-ns
COPY testdata/stats.o /opt/bpf/stats.o

ENTRYPOINT ["/bpfman-rpc"]
